package main

import (
	"archive/zip"
	"context"
	"encoding/json"
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// dockerManager is set once at boot by main.go so installers that need a
// real JVM (Forge / NeoForge) can run one-shot containers without threading
// a *DockerManager argument through the whole installer call graph.
var dockerManager *DockerManager

// SetDockerManager wires the package-level docker manager. Called from main
// right after NewDockerManager succeeds.
func SetDockerManager(dm *DockerManager) {
	dockerManager = dm
}

type InstallerConfig struct {
	Type      string `json:"type"`      // "paper", "vanilla", "fabric", "forge", "neoforge", "library", "upload", "upload-zip", "import", "backup", "modpack", "technic"
	Version   string `json:"version"`   // MC version, e.g. "1.21.1"
	Loader    string `json:"loader"`    // Optional loader/build version (Fabric loader, Forge build, NeoForge version)
	URL       string `json:"url"`       // Direct download URL (for "import" / library fallback / modpack .mrpack)
	Path      string `json:"path"`      // Local library file path (for "library" type)
	Structure string `json:"structure"` // "direct" or "subfolder" (for "upload-zip")
	// modpack metadata. Type="modpack" expects URL to be a
	// .mrpack hosted on cdn.modrinth.com; the handler downloads, extracts
	// overrides, fans out every listed mod, then chains into the underlying
	// loader install (paper/fabric/forge/neoforge) using Loader+Version
	// from the .mrpack manifest.
	ModrinthProjectID   string `json:"modrinthProjectId,omitempty"`
	ModrinthVersionID   string `json:"modrinthVersionId,omitempty"`
	ModrinthProjectSlug string `json:"modrinthProjectSlug,omitempty"`
	// JavaImage + ServerUUID flow in from the setup command so installers
	// that need a real JVM (Forge / NeoForge) can run inside a temp
	// container with the user's chosen Java image instead of relying on
	// `java` being installed on the node host.
	JavaImage  string `json:"javaImage,omitempty"`
	ServerUUID string `json:"serverUuid,omitempty"`
	// WipePaths names what to CLEAR before installing, as tokens rather than
	// paths - see installer_wipe.go. Empty means install on top of whatever is
	// there, which is what every install did before this existed and is still
	// the right answer for a plain jar swap.
	WipePaths []string `json:"wipePaths,omitempty"`
	// Technic pack ("technic"): Core resolves the pack and says which of the
	// three shapes it is (installer_technic.go); TechnicMods are a Solder
	// build's archives. The Minecraft version is read from the pack itself.
	Variant     string       `json:"variant,omitempty"`
	TechnicMods []TechnicMod `json:"technicMods,omitempty"`
}

// CleanServerJars removes server JARs and cached/generated directories while preserving
// user data like worlds, plugins, mods, configs, etc.
func CleanServerJars(subServerDir string) error {
	// Directories to remove (generated by the server / installer)
	// Note: "libraries" is kept — Forge/NeoForge needs it for runtime dependencies
	removeDirs := []string{"versions", "cache", ".fabric", ".gradle"}
	for _, dir := range removeDirs {
		p := filepath.Join(subServerDir, dir)
		if _, err := os.Stat(p); err == nil {
			log.Printf("Removing directory: %s", dir)
			os.RemoveAll(p)
		}
	}

	// Remove all JAR files in the root of the sub-server directory
	entries, err := os.ReadDir(subServerDir)
	if err != nil {
		return fmt.Errorf("failed to read sub-server dir: %v", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(strings.ToLower(entry.Name()), ".jar") {
			p := filepath.Join(subServerDir, entry.Name())
			log.Printf("Removing JAR: %s", entry.Name())
			os.Remove(p)
		}
	}

	return nil
}

// InstallServer installs the server software into <serverDataPath>/<subServerName>/.
// For "upload" type, files are already in place via HTTP upload — nothing to do.
//
// manifest is what the install turned out to DESCRIBE, and only the "backup"
// type ever produces one: a Dylaris backup archive carries its own description
// and Core has no copy of it, so the reader that unpacks the archive is the only
// place it can be read. Every other installer is something Core already
// described - Core picked the loader, so Core knows the loader - and returns nil.
func InstallServer(serverDataPath, subServerName string, config InstallerConfig) (manifest []byte, err error) {
	destDir := filepath.Join(serverDataPath, subServerName)
	if err := os.MkdirAll(destDir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create server dir: %v", err)
	}

	log.Printf("Starting Installation: %s (%s) -> %s", config.Type, config.Version, destDir)

	// Clear first, install second. The other order would delete files the
	// installer had just written - and on a failed install the operator would be
	// left with neither the old server nor the new one.
	if err := WipeBeforeInstall(destDir, config.WipePaths); err != nil {
		return nil, fmt.Errorf("preparing the directory failed: %w", err)
	}

	switch config.Type {
	case "paper":
		return nil, installPaper(destDir, config.Version)
	case "vanilla":
		return nil, installVanilla(destDir, config.Version)
	case "fabric":
		return nil, installFabric(destDir, config.Version, config.Loader)
	case "forge":
		return nil, installForge(destDir, config.Version, config.Loader, config.JavaImage, config.ServerUUID)
	case "neoforge":
		return nil, installNeoForge(destDir, config.Loader, config.JavaImage, config.ServerUUID)
	case "library":
		return nil, installFromLibrary(destDir, config.Path, config.URL)
	case "import":
		if config.URL == "" {
			return nil, fmt.Errorf("import type requires a URL")
		}
		return nil, installFromURL(destDir, config.URL)
	case "upload":
		// Files pre-uploaded via HTTP to the sub-server directory — nothing to do here.
		log.Printf("Upload type: files already in %s, skipping installer", destDir)
		return nil, nil
	case "upload-zip":
		return nil, installFromUploadZip(destDir, config.Structure)
	case "backup":
		// A Dylaris backup archive, uploaded into the sub-server directory the
		// same way an upload-zip install finds its zip there. The only installer
		// that reports something back: the archive describes itself.
		return installFromBackupArchive(destDir)
	case "modpack":
		return nil, installModpack(destDir, config)
	case "technic":
		return nil, installTechnic(destDir, config)
	default:
		return nil, fmt.Errorf("unknown installer type: %s", config.Type)
	}
}

// installFabric downloads the Fabric server launcher. Resolves loader/installer
// versions from Fabric's meta service when the caller leaves them blank.
// Result lands as fabric-server-launch.jar in destDir.
func installFabric(dir, mcVersion, loaderVersion string) error {
	if loaderVersion == "" {
		var loaders []struct {
			Loader struct {
				Version string `json:"version"`
				Stable  bool   `json:"stable"`
			} `json:"loader"`
		}
		if err := fetchJSON(fmt.Sprintf("https://meta.fabricmc.net/v2/versions/loader/%s", mcVersion), &loaders); err != nil {
			return fmt.Errorf("fabric loader lookup failed: %v", err)
		}
		for _, l := range loaders {
			if l.Loader.Stable {
				loaderVersion = l.Loader.Version
				break
			}
		}
		if loaderVersion == "" && len(loaders) > 0 {
			loaderVersion = loaders[0].Loader.Version
		}
		if loaderVersion == "" {
			return fmt.Errorf("no Fabric loader available for MC %s", mcVersion)
		}
	}

	// Pick the most recent stable installer (server-launcher itself is the
	// final artifact; this is just for the URL).
	var installers []struct {
		Version string `json:"version"`
		Stable  bool   `json:"stable"`
	}
	if err := fetchJSON("https://meta.fabricmc.net/v2/versions/installer", &installers); err != nil {
		return fmt.Errorf("fabric installer lookup failed: %v", err)
	}
	installerVersion := ""
	for _, i := range installers {
		if i.Stable {
			installerVersion = i.Version
			break
		}
	}
	if installerVersion == "" && len(installers) > 0 {
		installerVersion = installers[0].Version
	}
	if installerVersion == "" {
		return fmt.Errorf("no Fabric installer version available")
	}

	url := fmt.Sprintf("https://meta.fabricmc.net/v2/versions/loader/%s/%s/%s/server/jar",
		mcVersion, loaderVersion, installerVersion)
	log.Printf("Downloading Fabric server launcher (mc=%s loader=%s installer=%s)", mcVersion, loaderVersion, installerVersion)
	return downloadFile(url, filepath.Join(dir, "fabric-server-launch.jar"))
}

// installForge resolves the recommended/latest Forge build via promotions_slim.json
// (or uses the caller-supplied build), downloads the installer JAR and runs it
// inside a one-shot container built from the user's chosen Java image. No
// host-level Java install required.
func installForge(dir, mcVersion, build, javaImage, serverUUID string) error {
	if build == "" {
		var promos struct {
			Promos map[string]string `json:"promos"`
		}
		if err := fetchJSON("https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json", &promos); err != nil {
			return fmt.Errorf("forge promotions lookup failed: %v", err)
		}
		if b, ok := promos.Promos[mcVersion+"-recommended"]; ok {
			build = b
		} else if b, ok := promos.Promos[mcVersion+"-latest"]; ok {
			build = b
		}
		if build == "" {
			return fmt.Errorf("no Forge build available for MC %s", mcVersion)
		}
	}

	combined := mcVersion + "-" + build
	installerURL := fmt.Sprintf("https://maven.minecraftforge.net/net/minecraftforge/forge/%s/forge-%s-installer.jar", combined, combined)
	installerPath := filepath.Join(dir, "_forge-installer.jar")

	log.Printf("Downloading Forge installer (mc=%s build=%s)", mcVersion, build)
	if err := downloadFile(installerURL, installerPath); err != nil {
		return fmt.Errorf("forge installer download failed: %v", err)
	}
	defer os.Remove(installerPath)

	log.Printf("Running Forge --installServer inside %s ...", javaImage)
	return runJavaInstaller(serverUUID, filepath.Base(dir), javaImage, "_forge-installer.jar", "--installServer")
}

// installNeoForge resolves the requested NeoForge version (or latest if blank)
// from the Maven metadata, downloads the installer JAR and runs --install-server
// inside a one-shot Java container.
func installNeoForge(dir, version, javaImage, serverUUID string) error {
	if version == "" {
		resp, err := installerMetaClient.Get("https://maven.neoforged.net/releases/net/neoforged/neoforge/maven-metadata.xml")
		if err != nil {
			return fmt.Errorf("neoforge metadata fetch failed: %v", err)
		}
		defer resp.Body.Close()
		var meta struct {
			Versioning struct {
				Latest   string `xml:"latest"`
				Release  string `xml:"release"`
				Versions struct {
					Version []string `xml:"version"`
				} `xml:"versions"`
			} `xml:"versioning"`
		}
		if err := xml.NewDecoder(resp.Body).Decode(&meta); err != nil {
			return fmt.Errorf("neoforge metadata parse failed: %v", err)
		}
		if meta.Versioning.Release != "" {
			version = meta.Versioning.Release
		} else if meta.Versioning.Latest != "" {
			version = meta.Versioning.Latest
		} else if n := len(meta.Versioning.Versions.Version); n > 0 {
			version = meta.Versioning.Versions.Version[n-1]
		}
		if version == "" {
			return fmt.Errorf("no NeoForge version found in metadata")
		}
	}

	installerURL := fmt.Sprintf("https://maven.neoforged.net/releases/net/neoforged/neoforge/%s/neoforge-%s-installer.jar", version, version)
	installerPath := filepath.Join(dir, "_neoforge-installer.jar")

	log.Printf("Downloading NeoForge installer (version=%s)", version)
	if err := downloadFile(installerURL, installerPath); err != nil {
		return fmt.Errorf("neoforge installer download failed: %v", err)
	}
	defer os.Remove(installerPath)

	log.Printf("Running NeoForge --install-server inside %s ...", javaImage)
	return runJavaInstaller(serverUUID, filepath.Base(dir), javaImage, "_neoforge-installer.jar", "--install-server")
}

// runJavaInstaller wraps the installer-JAR execution inside a one-shot Java
// container. The sub-server directory (not the server root) is mounted at
// /data so /data/<installerJAR> resolves where the JAR was actually
// downloaded to. Previously the bind mounted the server root and the cmd
// looked for the JAR at /data/_forge-installer.jar — but the JAR lives in
// <server-dir>/<sub-server>/_forge-installer.jar, so Java exited 1 with
// no useful stderr (JVM "Unable to access jarfile" beats stdcopy to it).
func runJavaInstaller(serverUUID, subServerName, javaImage, installerJAR string, args ...string) error {
	if dockerManager == nil {
		return fmt.Errorf("docker manager unavailable — installer cannot run")
	}
	if javaImage == "" {
		return fmt.Errorf("installer requires a Java image (set during setup)")
	}
	if subServerName == "" {
		return fmt.Errorf("installer requires a sub-server name (cannot resolve mount path)")
	}
	cmd := append([]string{"java", "-jar", "/data/" + installerJAR}, args...)
	logs, err := dockerManager.RunInstallerContainer(context.Background(), serverUUID, subServerName, javaImage, cmd)
	if err != nil {
		if logs != "" {
			return fmt.Errorf("%w\n%s", err, logs)
		}
		return err
	}
	return nil
}

// fetchJSON is a tiny helper that fetches a URL and decodes JSON into target.
func fetchJSON(url string, target interface{}) error {
	resp, err := installerMetaClient.Get(url)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("bad status %s", resp.Status)
	}
	return json.NewDecoder(resp.Body).Decode(target)
}

// installPaper fetches the latest PaperMC build for the given version and
// downloads it as server.jar. Uses the v3 Fill API; the old api.papermc.io/v2
// was retired (now returns 410 "sunset"). The v3 builds/latest response carries
// the direct download URL, so there is no longer a URL to reconstruct.
func installPaper(dir, version string) error {
	apiURL := fmt.Sprintf("https://fill.papermc.io/v3/projects/paper/versions/%s/builds/latest", version)
	resp, err := installerMetaClient.Get(apiURL)
	if err != nil {
		return fmt.Errorf("failed to query PaperMC API: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("PaperMC API returned HTTP %d for version %s", resp.StatusCode, version)
	}

	var result struct {
		ID        int `json:"id"`
		Downloads map[string]struct {
			Name string `json:"name"`
			URL  string `json:"url"`
		} `json:"downloads"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return fmt.Errorf("failed to parse PaperMC response: %v", err)
	}
	dl, ok := result.Downloads["server:default"]
	if !ok || dl.URL == "" {
		return fmt.Errorf("no server download available for Paper %s", version)
	}

	log.Printf("Downloading PaperMC %s build %d ...", version, result.ID)
	return downloadFile(dl.URL, filepath.Join(dir, "server.jar"))
}

// installVanilla downloads the official Minecraft server jar via Mojang's launcher manifest.
func installVanilla(dir, version string) error {
	const manifestURL = "https://launchermeta.mojang.com/mc/game/version_manifest.json"

	resp, err := installerMetaClient.Get(manifestURL)
	if err != nil {
		return fmt.Errorf("failed to fetch Mojang manifest: %v", err)
	}
	defer resp.Body.Close()

	var manifest struct {
		Versions []struct {
			ID  string `json:"id"`
			URL string `json:"url"`
		} `json:"versions"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&manifest); err != nil {
		return fmt.Errorf("failed to parse Mojang manifest: %v", err)
	}

	var versionURL string
	for _, v := range manifest.Versions {
		if v.ID == version {
			versionURL = v.URL
			break
		}
	}
	if versionURL == "" {
		return fmt.Errorf("vanilla version %s not found in Mojang manifest", version)
	}

	resp2, err := installerMetaClient.Get(versionURL)
	if err != nil {
		return fmt.Errorf("failed to fetch version info for %s: %v", version, err)
	}
	defer resp2.Body.Close()

	var versionInfo struct {
		Downloads struct {
			Server struct {
				URL string `json:"url"`
			} `json:"server"`
		} `json:"downloads"`
	}
	if err := json.NewDecoder(resp2.Body).Decode(&versionInfo); err != nil {
		return fmt.Errorf("failed to parse version info: %v", err)
	}
	if versionInfo.Downloads.Server.URL == "" {
		return fmt.Errorf("no server download available for vanilla %s", version)
	}

	log.Printf("Downloading Vanilla Minecraft %s ...", version)
	return downloadFile(versionInfo.Downloads.Server.URL, filepath.Join(dir, "server.jar"))
}

// installFromLibrary copies a library file (JAR or ZIP) into the server directory.
// localPath takes priority; fallbackURL is used when localPath is empty.
func installFromLibrary(destDir, localPath, fallbackURL string) error {
	if localPath != "" {
		return installFromLocalFile(destDir, localPath)
	}
	if fallbackURL != "" {
		return installFromURL(destDir, fallbackURL)
	}
	return fmt.Errorf("library installer: no path or URL provided")
}

// installFromLocalFile copies a local file (JAR or ZIP) or directory into destDir.
func installFromLocalFile(destDir, srcPath string) error {
	info, err := os.Stat(srcPath)
	if err != nil {
		return fmt.Errorf("library source not found: %v", err)
	}
	if info.IsDir() {
		log.Printf("Copying directory from library: %s", srcPath)
		return copyDir(srcPath, destDir)
	}
	lower := strings.ToLower(srcPath)
	if strings.HasSuffix(lower, ".zip") {
		log.Printf("Extracting ZIP from library: %s", srcPath)
		return extractZipToDir(srcPath, destDir)
	}
	// Assume it's a JAR or similar — place it as server.jar
	log.Printf("Copying JAR from library: %s", srcPath)
	return copyFileForTenant(srcPath, filepath.Join(destDir, "server.jar"))
}

// installFromURL downloads a file from a URL and places it in destDir.
// ZIPs are extracted automatically; other files are saved as server.jar.
func installFromURL(destDir, url string) error {
	lower := strings.ToLower(url)

	var destPath string
	if strings.HasSuffix(lower, ".zip") {
		destPath = filepath.Join(destDir, "_download.zip")
	} else {
		destPath = filepath.Join(destDir, "server.jar")
	}

	log.Printf("Downloading from URL: %s ...", url)
	if err := downloadFile(url, destPath); err != nil {
		return err
	}

	if strings.HasSuffix(destPath, ".zip") {
		log.Printf("Extracting downloaded ZIP ...")
		if err := extractZipToDir(destPath, destDir); err != nil {
			return err
		}
		os.Remove(destPath)
	}
	return nil
}

// installFromUploadZip extracts a pre-uploaded .upload.zip in the sub-server directory.
// If structure is "subfolder", it detects a single top-level folder and moves its contents up.
func installFromUploadZip(destDir, structure string) error {
	zipPath := filepath.Join(destDir, ".upload.zip")
	if _, err := os.Stat(zipPath); err != nil {
		return fmt.Errorf("upload zip not found at %s", zipPath)
	}

	log.Printf("Extracting uploaded ZIP: %s (structure=%s)", zipPath, structure)
	if err := extractZipToDir(zipPath, destDir); err != nil {
		return fmt.Errorf("failed to extract upload zip: %v", err)
	}
	os.Remove(zipPath)

	// If structure is "subfolder", check for a single top-level directory and move contents up
	if structure == "subfolder" {
		entries, err := os.ReadDir(destDir)
		if err != nil {
			return nil // extraction succeeded, this is non-critical
		}
		var dirs []os.DirEntry
		for _, e := range entries {
			if e.IsDir() {
				dirs = append(dirs, e)
			}
		}
		if len(dirs) == 1 {
			subDir := filepath.Join(destDir, dirs[0].Name())
			log.Printf("Moving contents from subfolder: %s", dirs[0].Name())
			subEntries, err := os.ReadDir(subDir)
			if err != nil {
				return nil
			}
			for _, e := range subEntries {
				src := filepath.Join(subDir, e.Name())
				dst := filepath.Join(destDir, e.Name())
				os.Rename(src, dst)
			}
			os.Remove(subDir)
		}
	}

	return nil
}

// DetectServerJar scans the server directory for the main JAR file.
// Returns the detected JAR filename (e.g. "forge-1.20.1-47.2.0-shim.jar") or "server.jar" as fallback.
func DetectServerJar(destDir string) string {
	patterns := []string{
		"forge-*-shim.jar",      // Forge 1.17+ (new launcher)
		"forge-*-universal.jar", // Forge legacy
		// Forge 1.12-1.16: the installer writes forge-<mc>-<build>.jar (measured
		// with the real 1.12.2 and 1.16.5 installers). Listed after the two
		// specific shapes so a 1.17+ directory still picks its shim.
		"forge-*.jar",
		"neoforge-*.jar",           // NeoForge
		"fabric-server-launch.jar", // Fabric
		"paper-*.jar",              // Paper
		"purpur-*.jar",             // Purpur
		"server.jar",               // Default
	}
	for _, pattern := range patterns {
		matches, _ := filepath.Glob(filepath.Join(destDir, pattern))
		for _, m := range matches {
			// A leftover installer sorts BEFORE its jar ('-' < '.') and is not
			// a server.
			if strings.HasSuffix(m, "-installer.jar") {
				continue
			}
			jar := filepath.Base(m)
			log.Printf("Detected server JAR: %s", jar)
			return jar
		}
	}
	return "server.jar"
}

// extractZipToDir extracts a ZIP archive into destDir. Entries are created
// THROUGH an os.Root at destDir, so a symlink planted in destDir (over SFTP,
// beam, or from inside the tenant's container) cannot be followed out of it,
// and traversal names are folded away by extractRel first.
func extractZipToDir(zipPath, destDir string) error {
	r, err := zip.OpenReader(zipPath)
	if err != nil {
		return fmt.Errorf("failed to open zip %s: %v", zipPath, err)
	}
	defer r.Close()

	root, err := openRootMk(destDir)
	if err != nil {
		return err
	}
	defer root.Close()

	for _, f := range r.File {
		name, skip := extractSkip(destDir, f.Name)
		if skip {
			log.Printf("Skipping unsafe zip entry %q", f.Name)
			continue
		}
		if f.FileInfo().IsDir() {
			root.MkdirAll(name, 0o755)
			continue
		}
		rc, err := f.Open()
		if err != nil {
			return err
		}
		werr := writeFileInto(root, name, f.Mode(), rc, 0)
		rc.Close()
		if werr != nil {
			return werr
		}
	}
	return nil
}

// copyDir DUPLICATES src into dst for a user: protected entries dropped,
// everything handed to the container's uid, both ends confined through an
// os.Root (see copyDirInto in rootfs.go).
func copyDir(src, dst string) error { return copyDirInto(src, dst) }

// copyTree copies src into dst VERBATIM, protected entries included. Only a
// whole-server MOVE may use it.
func copyTree(src, dst string) error { return copyTreeInto(src, dst) }

// copyFileForTenant copies one file into a server's own data and hands it to
// the container's uid.
func copyFileForTenant(src, dst string) error { return copyFileInto(src, dst) }

// downloadFile downloads a URL to a local file path.
func downloadFile(url, destPath string) error {
	return downloadFileWithin(url, destPath, installerStallTimeout)
}

// downloadFileWithin is downloadFile with the stall window injectable, so the
// behaviour can be tested without waiting a minute.
//
// The window bounds SILENCE, not duration: it is reset by every read that
// returns bytes, so a slow-but-progressing transfer runs as long as it needs
// while a peer that sends headers and then stops is abandoned. That gap was the
// one the Transport timeouts could not close - ResponseHeaderTimeout stops
// covering the moment the headers arrive - and it lands the server in
// `installing` forever, which is worse than a failed install because a failure
// can be retried.
func downloadFileWithin(url, destPath string, stall time.Duration) error {
	return downloadWith(installerDownloadClient, url, destPath, stall, 0)
}

// downloadWith is the shared body: client chooses the dial policy, maxBytes > 0
// caps the body (0 = no cap).
func downloadWith(client *http.Client, url, destPath string, stall time.Duration, maxBytes int64) error {
	// Created THROUGH a Root at the destination's directory so a symlink planted
	// at destPath (the sub-server dir is tenant-writable) is refused rather than
	// followed. The directory is node-chosen and already made by the installer.
	root, err := os.OpenRoot(filepath.Dir(destPath))
	if err != nil {
		return err
	}
	defer root.Close()
	out, err := root.Create(filepath.Base(destPath))
	if err != nil {
		return err
	}
	defer out.Close()

	// Cancelling the request context is what actually unblocks a stalled read;
	// closing the body from another goroutine is not safe.
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return err
	}
	resp, err := client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("bad status: %s", resp.Status)
	}

	watchdog := time.AfterFunc(stall, cancel)
	defer watchdog.Stop()

	var dst io.Writer = out
	if maxBytes > 0 {
		dst = &cappedWriter{w: out, left: maxBytes}
	}
	_, err = io.Copy(dst, &stallGuard{r: resp.Body, timer: watchdog, window: stall})
	if errors.Is(err, errDownloadTooLarge) {
		return fmt.Errorf("%w (%d bytes)", errDownloadTooLarge, maxBytes)
	}
	if err != nil && ctx.Err() != nil {
		return fmt.Errorf("download stalled: no data for %s", stall)
	}
	return err
}

// deadlineTimer is the part of *time.Timer stallGuard uses. Narrowed to an
// interface so the reset behaviour can be asserted directly instead of inferred
// from how long a download took: the end-to-end version of that test sleeps its
// way through real chunks and has now failed twice on a loaded CI runner, once
// at a 3.3x timing margin and once at 15x. The property is "a read carrying
// bytes pushes the deadline back", which owes nothing to the clock.
type deadlineTimer interface {
	Reset(time.Duration) bool
}

// stallGuard pushes the watchdog back on every read that produced bytes.
type stallGuard struct {
	r      io.Reader
	timer  deadlineTimer
	window time.Duration
}

func (s *stallGuard) Read(p []byte) (int, error) {
	n, err := s.r.Read(p)
	if n > 0 {
		s.timer.Reset(s.window)
	}
	return n, err
}
