package store

import (
	"database/sql"
	"time"
)

// SolderClient is a Technic Launcher client identity used to whitelist private
// packs. uuid is generated by PostgreSQL and is what the launcher sends as ?cid=.
type SolderClient struct {
	ID        int       `json:"id"`
	UUID      string    `json:"uuid"`
	Name      string    `json:"name"`
	OwnerID   string    `json:"ownerId"`
	CreatedAt time.Time `json:"createdAt"`
}

// SolderKey is a global Solder API key. Only the sha256 hash is stored; the
// plaintext is shown once at creation and never persisted.
type SolderKey struct {
	ID        int       `json:"id"`
	Name      string    `json:"name"`
	OwnerID   string    `json:"ownerId"`
	CreatedAt time.Time `json:"createdAt"`
}

func scanSolderClient(row interface{ Scan(...interface{}) error }) (*SolderClient, error) {
	var c SolderClient
	if err := row.Scan(&c.ID, &c.UUID, &c.Name, &c.OwnerID, &c.CreatedAt); err != nil {
		return nil, err
	}
	return &c, nil
}

func (s *PostgresStore) CreateSolderClient(name, ownerID string) (*SolderClient, error) {
	var c SolderClient
	err := s.db.QueryRow(
		`INSERT INTO solder_clients (name, owner_id) VALUES ($1, $2)
		 RETURNING id, uuid, name, owner_id, created_at`,
		name, ownerID).Scan(&c.ID, &c.UUID, &c.Name, &c.OwnerID, &c.CreatedAt)
	if err != nil {
		return nil, err
	}
	return &c, nil
}

func (s *PostgresStore) ListSolderClientsByOwner(ownerID string) ([]SolderClient, error) {
	rows, err := s.db.Query(
		`SELECT id, uuid, name, owner_id, created_at FROM solder_clients
		 WHERE owner_id = $1 ORDER BY created_at DESC`, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	clients := make([]SolderClient, 0)
	for rows.Next() {
		c, err := scanSolderClient(rows)
		if err != nil {
			return nil, err
		}
		clients = append(clients, *c)
	}
	return clients, rows.Err()
}

// GetSolderClient fetches one client scoped to its owner (nil, nil if not found
// for this owner).
func (s *PostgresStore) GetSolderClient(id int, ownerID string) (*SolderClient, error) {
	row := s.db.QueryRow(
		`SELECT id, uuid, name, owner_id, created_at FROM solder_clients
		 WHERE id = $1 AND owner_id = $2`, id, ownerID)
	c, err := scanSolderClient(row)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	return c, err
}

func (s *PostgresStore) DeleteSolderClient(id int, ownerID string) error {
	_, err := s.db.Exec(`DELETE FROM solder_clients WHERE id = $1 AND owner_id = $2`, id, ownerID)
	return err
}

// GetSolderClientByUUID resolves a launcher ?cid= to a client (nil, nil if none).
// Not owner-scoped: the public read path has no caller identity.
func (s *PostgresStore) GetSolderClientByUUID(uuid string) (*SolderClient, error) {
	row := s.db.QueryRow(
		`SELECT id, uuid, name, owner_id, created_at FROM solder_clients WHERE uuid = $1`, uuid)
	c, err := scanSolderClient(row)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	return c, err
}

func (s *PostgresStore) AddPackClient(packID, clientID int) error {
	_, err := s.db.Exec(
		`INSERT INTO pack_clients (pack_id, client_id) VALUES ($1, $2)
		 ON CONFLICT (pack_id, client_id) DO NOTHING`, packID, clientID)
	return err
}

func (s *PostgresStore) RemovePackClient(packID, clientID int) error {
	_, err := s.db.Exec(`DELETE FROM pack_clients WHERE pack_id = $1 AND client_id = $2`, packID, clientID)
	return err
}

func (s *PostgresStore) ListPackClients(packID int) ([]SolderClient, error) {
	rows, err := s.db.Query(
		`SELECT c.id, c.uuid, c.name, c.owner_id, c.created_at
		 FROM pack_clients pc JOIN solder_clients c ON c.id = pc.client_id
		 WHERE pc.pack_id = $1 ORDER BY c.created_at DESC`, packID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	clients := make([]SolderClient, 0)
	for rows.Next() {
		c, err := scanSolderClient(rows)
		if err != nil {
			return nil, err
		}
		clients = append(clients, *c)
	}
	return clients, rows.Err()
}

func (s *PostgresStore) IsPackClient(packID, clientID int) (bool, error) {
	var one int
	err := s.db.QueryRow(
		`SELECT 1 FROM pack_clients WHERE pack_id = $1 AND client_id = $2`, packID, clientID).Scan(&one)
	if err == sql.ErrNoRows {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

func (s *PostgresStore) CreateSolderKey(name, ownerID, keyHash string) (*SolderKey, error) {
	var k SolderKey
	err := s.db.QueryRow(
		`INSERT INTO solder_keys (key_hash, name, owner_id) VALUES ($1, $2, $3)
		 RETURNING id, name, owner_id, created_at`,
		keyHash, name, ownerID).Scan(&k.ID, &k.Name, &k.OwnerID, &k.CreatedAt)
	// key_hash is UNIQUE, and since an operator may PASTE a key rather than
	// only mint one, a collision is now something a person can cause by hand -
	// re-adding the same Technic key, or adding one somebody else already holds.
	// It has to come back as an answer rather than as a 500, and never as the
	// driver's message, which spells out the table and the constraint.
	if isUniqueViolation(err) {
		return nil, ErrNameTaken
	}
	if err != nil {
		return nil, err
	}
	return &k, nil
}

func (s *PostgresStore) ListSolderKeysByOwner(ownerID string) ([]SolderKey, error) {
	rows, err := s.db.Query(
		`SELECT id, name, owner_id, created_at FROM solder_keys
		 WHERE owner_id = $1 ORDER BY created_at DESC`, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	keys := make([]SolderKey, 0)
	for rows.Next() {
		var k SolderKey
		if err := rows.Scan(&k.ID, &k.Name, &k.OwnerID, &k.CreatedAt); err != nil {
			return nil, err
		}
		keys = append(keys, k)
	}
	return keys, rows.Err()
}

func (s *PostgresStore) DeleteSolderKey(id int, ownerID string) error {
	_, err := s.db.Exec(`DELETE FROM solder_keys WHERE id = $1 AND owner_id = $2`, id, ownerID)
	return err
}

// GetSolderKeyByHash resolves a hashed ?k= (or /verify/{key}) to a key
// (nil, nil if none). The caller hashes the plaintext with hashAuthToken first.
func (s *PostgresStore) GetSolderKeyByHash(keyHash string) (*SolderKey, error) {
	var k SolderKey
	err := s.db.QueryRow(
		`SELECT id, name, owner_id, created_at FROM solder_keys WHERE key_hash = $1`, keyHash).
		Scan(&k.ID, &k.Name, &k.OwnerID, &k.CreatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &k, nil
}
